version: "3.9"
services:
  next:
    image: ardere/hunters.host:latest
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - ROOT_URL=http://hunters.host
      - MONGO_URL=mongodb://mongo:27017/meteor
      - PORT=3000

  mongo:
    image: webhippie/mongodb:latest-arm32v7
    command: mongod --storageEngine=wiredTiger